### ISSUE TITLE
Uncomment Image Processing and install action text

### ISSUE THREAD

**Issue by andyweiss1982** [wyncode/C33_adrian_jevon_lazaro_yujailec#10]
Uncomment this line

https://github.com/wyncode/C33_adrian_jevon_lazaro_yujailec/blob/d35ee15ebdaebee916cae5bed568ad2b19f056bd/Gemfile#L26

then  

`bundle`

then

`rails action_text:install`

**Comment by Limlight86** [comment]
I had to install imagemagick with brew to get the images I dragged in to save after creating a new entry.

**Comment by andyweiss1982** [comment]
That makes sense.   Every team member will have to do the same.  The image processing gem uses imagemagick under the hood.
